### ISSUE TITLE
关于目前发现的部分翻译问题以及一些建议

### ISSUE THREAD

**Issue by KrukaL** [soarqin/ConvergenceER_CN#1]
目前发现的部分翻译问题：
1、【堕焰】祷告体系的初级圣印记【Fire Monk's Seal】发现了翻译错误：首先是物品名称中的【Fire Monk's Seal】被翻译为了【火焰主教圣印记】，但是这里的Fire Monk应该是【火の僧兵/火焰习武修士】，火焰主教对应的词是Prelate；其次是物品说明中【A sacred seal used by wielders of the Giantsflame.】这一句的翻译中有个错字，【巨人火焰挥舞者】被写成了【巨人火焰挥舞着】。
2、武器【黑焰之剑】，物品名称原文为【Fell Flame Sword】，应该译作“堕焰之剑”。
3、【War Surgeon's Seal/战场医师圣印记】和【Mohgwyn Seal/蒙格温圣印记】的物品说明中，【Bloodflame Affinity】应为【血焰属性加成】，目前被写成【黑焰属性加成】。
4、【龙信仰圣印记】的物品说明中，【Dragon Cult Affinity】应作【龙信仰属性加成】，目前被写成【龙祷告属性加成】。
5、【血焰】和【狩猎神祇（弑神）】两种祷告体系的对应增伤物品的描述文本中，【This weapon increases the damage of Bloodflame incantations by 10% / 这把武器能提升10%血焰祷告攻击力】和【This weapon increases the damage of Godslayer incantations by 10% / 这把武器能提升10%弑神祷告攻击力】，这两句中的【祷告攻击力】目前都被写成【魔法攻击力】。
6、【龙信仰】祷告体系的对应增伤物品，盾牌【龙信仰纹章】的物品说明中，”A gravelstone kite shield emblazoned with the golden sigil of the Dragon Cult of Leyndell.“（一面碎石鳶盾，饰有罗德尔龙信仰的金色纹章）这句中的”鸢“字用成了繁体，导致在游戏中这个字会变成方块乱码。
7、【黑夜】魔法体系的对应增伤物品【Midnight Dagger】应该译作【子夜短刀】，这里写成了【癫狂黄铜短刀】。
8、若干武器与魔法的描述文本中有【the fallen Nox Empire】，应是指”已陨落的诺克斯帝国“，而非”堕落的诺克斯帝国“。
9、对于祷告体系【神秘/祖灵】的对应职业“The Mystic”有前后写法不一致，有些地方为“神秘学者”，有些地方则是“神秘使者”。
10、战灰质变选项中的【Lava】，正确应译为【熔岩】，这里错写成了【沼泽】。
11、战灰质变选项中的【Flame】，根据您对武器名称前缀的翻译应作【火焰】，但是在菜单文本仍然写为【焰术】。
12、法术描述中的【underworld】应该是指【地下世界】而非【冥界】。
13、【land between/lands between】在部分文本中被翻译为了【阴阳界】。
14、【能量盾】法术描述中的【Haima Conspectus】是【海摩教室】而非【海摩大锤】。
15、蒙格大卢恩描述中有误，已经没有【并在入侵时，能获得“大卢恩幻影”。】的效果了。
16、玛莲妮娅大卢恩描述中漏掉了【每次命中回复3%血量】。
17、法术【辉光球】的描述文本中，【Perhaps the golems that are able to wield this power are empowered by the souls of fallen sorcerers, thereby creating a new iteration of glintstone manipulation.】这一句，根据文意应该是【死去魔法师的灵魂】？死去战士的灵魂使之活动，死去魔法师的灵魂为之供能。
18、【primeval current】应作“起源”而非”起始源流“。

若干建议：
1、祷告体系以及战灰质变中的【Godslayer】这里都翻译成了“弑神‘，Godslayer这个在原版中正是【神狩り/狩猎神祇】的英文对应词，是否换回【狩猎神祇】会更好？这样也可以将一般黑焰祷告跟MOD中该体系最上次祷告之一的”Deicide/弑杀神祇“相区分。
2、魔法体系【Aberrant】，这里译作“荆棘”，但是参照原版文本的描述，应该对应的是“异端”一词；在MOD中这一魔法体系也不只包含若干荆棘魔法，同样包括让自己流血痛苦并借此施展的法术；在原版中两种荆棘魔法被成为”Aberrant/异端“也是因为他们施法并非依靠智慧以及天然辉石，而是要凭借信仰以及流血的痛苦。
3、【龙信仰】祷告以及锻造石名称的“古代”，也许可以处理为“古龙”？
4、祷告体系【Mystic】使用”神秘“一词，感觉可能会与原版的神秘质变弄混。如果使用”密契“一次呢？这个提议是因为现实中的”密契主义“（Mysticism）有一个重要方面就是重视精神与高等精神实体的契合；而MOD这一祷告体系是由祖灵信仰与米凯拉/托莉娜信仰糅合而成，也很重视精神方面的升格，个人感觉可能比较相符。

其实在NEXUS那边已经反馈过，不过因为最近才看到您的github项目，所以也冒昧地搬到这边来了。
最后感谢您的翻译以及打包工具。

**Comment by soarqin** [comment]
感谢提出意见，我会尽快一一检讨。如果有能力的话也欢迎提交PR。

**Comment by KrukaL** [comment]
您好，我已pull request，同时附上了详细的修改说明，您可以一一查看各处修改前后的对照；若是有感觉不合理的地方也请告诉我；因为部分修改是基于个人理解，可能会存在偏差

**Comment by KrukaL** [comment]
您好，1.3版本已经开放下载，不知您这里还会继续进行翻译吗？如果会继续的话，也请允许我参与进翻译项目中谢谢！
另外又提交了一个pull request，主要是在1.3开始翻译之前又进行了一次检查，发现了magic damage有被错译的情况。
