### ISSUE TITLE
翻译有缺失

### ISSUE THREAD

**Issue by OnlineZ0** [soarqin/ConvergenceER_CN#12]
我很感谢您的汉化，但是我发现部分职业的武器指引说明有缺失，比如腐败眷属和野兽的武器说明缺失

**Comment by RKOJIN** [comment]
我去游戏里看了一下，确实如此，希望作者可以修复一下

**Comment by soarqin** [comment]
已在20240320更新中修复，感谢bug反馈

**Comment by OnlineZ0** [comment]
> 已在20240320更新中修复，感谢bug反馈

感谢
