### ISSUE TITLE
法魂2.1发布了

### ISSUE THREAD

**Issue by RKOJIN** [soarqin/ConvergenceER_CN#20]
不知道作者您玩dlc了吗？还会继续汉化吗？

**Comment by RKOJIN** [comment]
刚发现法魂2.1还是内测状态，不好意思 有点太着急了

**Comment by soarqin** [comment]
在外旅游才回来，我去看看

**Comment by RKOJIN** [comment]
好的，目前法魂只在discord/下载器里发布了2.0.1版本（内测），n网还没更新

**Comment by RKOJIN** [comment]
> 在外旅游才回来，我去看看

好的，目前法魂只在discord/下载器里发布了2.0.1版本（内测），n网还没更新
