### ISSUE TITLE
1.2版本的汉化补丁有个地方的翻译错误太大了

### ISSUE THREAD

**Issue by RKOJIN** [soarqin/ConvergenceER_CN#6]
![EFN@P{FVH%O3U${2IM3Z7RF](https://github.com/soarqin/ConvergenceER_CN/assets/115261210/022a5200-2f1f-4169-aff0-fda870f9c782)

这个技能的实际效果是回血，希望在1.3版本翻译的更新中可以修正，其他地方的错误更多只是让人摸不着头脑，这个错译让我的游戏体验大打折扣

**Comment by KrukaL** [comment]
收到，此处已进行修正

**Comment by soarqin** [comment]
在#5中已经修正
