### ISSUE TITLE
关于天空城赐福点名称的修正

### ISSUE THREAD

**Issue by KrukaL** [soarqin/ConvergenceER_CN#8]
抱歉又提交了一个pull request，刚刚在游玩过程中发现的问题。
先前对Dragonlord's Annex的翻译应该是有误的，MOD中把古龙兰斯桑克斯boss战也挪到了天空城，这个位置就是兰斯桑克斯的boss房前篝火，加上annex意思应该是附属建筑，所以我翻译为“龙王偏殿“了。

**Comment by KrukaL** [comment]
不过也可以先不用merge，这两天我正在对法术部分整体校对一遍

**Comment by soarqin** [comment]
close due to #7
